# Generated by Django 4.0.8 on 2022-11-07 10:09

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Text', required=True))])), ('richtext', streams.blocks.RichTextBlock()), ('card', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your Title', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('Image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(max_length=50, required=True)), ('button', wagtail.blocks.PageChooserBlock(required=True)), ('button_url', wagtail.blocks.URLBlock(required=False))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
